-- V1__init.sql
-- Created at: 2026-02-14

CREATE TABLE IF NOT EXISTS roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS auth_accounts
(
    id            UUID         NOT NULL PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    verified      BOOLEAN      NOT NULL DEFAULT FALSE,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    type          VARCHAR(50)  NOT NULL CHECK (type IN ('USER', 'ASSOCIATION')),
    owner_id      UUID         NOT NULL
);

CREATE TABLE IF NOT EXISTS auth_account_roles
(
    auth_account_id UUID   NOT NULL,
    role_id         BIGINT NOT NULL,
    PRIMARY KEY (auth_account_id, role_id),
    CONSTRAINT fk_auth_account_roles_account
        FOREIGN KEY (auth_account_id) REFERENCES auth_accounts (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_auth_account_roles_role
        FOREIGN KEY (role_id) REFERENCES roles (id)
            ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS refresh_tokens
(
    id                   UUID         NOT NULL PRIMARY KEY,
    token                VARCHAR(255) NOT NULL UNIQUE,
    auth_account_id      UUID         NOT NULL,
    ip_address           VARCHAR(45),
    user_agent           VARCHAR(512),
    device_id            VARCHAR(128),
    created_at           TIMESTAMPTZ  NOT NULL,
    expires_at           TIMESTAMPTZ  NOT NULL,
    revoked              BOOLEAN      NOT NULL DEFAULT FALSE,
    replacement_token_id UUID,

    CONSTRAINT fk_refresh_tokens_account
        FOREIGN KEY (auth_account_id) REFERENCES auth_accounts (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_refresh_tokens_replacement
        FOREIGN KEY (replacement_token_id) REFERENCES refresh_tokens (id)
            ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_refresh_token_auth_account
    ON refresh_tokens (auth_account_id);

CREATE INDEX IF NOT EXISTS idx_refresh_token_token
    ON refresh_tokens (token);

CREATE TABLE IF NOT EXISTS users
(
    id       UUID         NOT NULL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS regions
(
    code VARCHAR(10)  NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS departments
(
    code        VARCHAR(10)  NOT NULL PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    region_code VARCHAR(10)  NOT NULL,

    CONSTRAINT fk_departments_region
        FOREIGN KEY (region_code) REFERENCES regions (code)
            ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS tags
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code  VARCHAR(255) NOT NULL UNIQUE,
    label VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS associations
(
    id          UUID         NOT NULL PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_associations_name
    ON associations (name);

CREATE TABLE IF NOT EXISTS association_tags
(
    association_id UUID   NOT NULL,
    tag_id         BIGINT NOT NULL,
    PRIMARY KEY (association_id, tag_id),

    CONSTRAINT fk_association_tags_association
        FOREIGN KEY (association_id) REFERENCES associations (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_association_tags_tag
        FOREIGN KEY (tag_id) REFERENCES tags (id)
            ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS association_departments
(
    association_id  UUID        NOT NULL,
    department_code VARCHAR(10) NOT NULL,
    PRIMARY KEY (association_id, department_code),

    CONSTRAINT fk_association_departments_association
        FOREIGN KEY (association_id) REFERENCES associations (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_association_departments_department
        FOREIGN KEY (department_code) REFERENCES departments (code)
            ON DELETE RESTRICT
);