-- V2__post.sql

CREATE TABLE IF NOT EXISTS posts
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                 VARCHAR(255) NOT NULL,
    content_source        TEXT NOT NULL,
    content_rendered_html TEXT NOT NULL,
    posted_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    modified_at           TIMESTAMPTZ,
    owner_id              UUID NOT NULL,

    CONSTRAINT fk_posts_owner
        FOREIGN KEY (owner_id) REFERENCES associations (id)
            ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_posts_owner_posted_at
    ON posts (owner_id, posted_at DESC);
